version: '3.9'

services:
  database:
    image: mysql:5.7
    container_name: database_hati
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysqldata:/data/mysql
      - ./hatiData.sql:/docker-entrypoint-initdb.d/hatiData.sql

  # app:
  #   build: .
  #   container_name: node_hati
  #   restart: always
  #   ports:
  #     - 3001:3001
  #     - 9229:9229
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database
  #   depends_on:
  #     - database

volumes:
  mysqldata:
    driver: local
